Repository AGH-Narzedzia-Informatyczne-2023-2024/kidang-tikus, pull requests merged in 2023-11, with the labels that each got.

#10 Client setup
  .editorconfig
  client/main.py
  client/requirements.txt
Labels: enhancement, urgent

#8 Add server application
  server/Dockerfile
  server/requirements.txt
  server/src/app.py
Labels: multiplayer

#12 Jbanasik
  Sieve.py
Labels: enhancement, urgent

#17 added sqrt function
  sqrt.py
Labels: good first issue

#15 Create average.py
  average.py
Labels: good first issue
